version: '3.5'

services:
  front-end:
    build:
      context: ./frontend
    ports:
      - 5000:5000
    container_name: frontend_exercise
  back-end:
    build:
      context: ./backend
    ports:
      - 8000:8000
    container_name: backend_exercise
